apiVersion: v1
kind: Service
metadata:
  name: ingress-controller-kong-udp
  namespace: kong-system
spec:
  ports:
  - protocol: UDP
    port: 9999
    targetPort: 9999
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: ingress-controller
    app.kubernetes.io/name: kong
  type: LoadBalancer
